[package]
name = "bluster"
version = "0.12.0"
edition = "2021"

[lib]
name = "bluster"
path = "../../src/lib.rs"

[dependencies]
nalgebra = "0.31.0"
parry3d = "0.9.0"
serde = { version = "1", features = [ "derive" ], optional = true }